### ISSUE TITLE
I would like to have the ability to search through existing activities

### ISSUE THREAD

**Issue by benbakhar** [omrilotan/doowat#13]
## Feature Description
As the activity list will grow it will be nice to be able to search through existing activities so one won't suggest an activity which already exist.

Big Like for the Project btw!

**Comment by omrilotan** [comment]
😋 definitely going in the TODO pile 🔍

**Comment by omrilotan** [comment]
@benbakhar added in 676362a

Glossary page has been added a search input
![](https://user-images.githubusercontent.com/516342/71041590-23261080-2132-11ea-88a0-073c88eaba4c.gif)
